const advisoryBoardMembers = [
  {
    name: "Dr. Ranie B. Canlas",
    title: "Vice President for Research, Innovation, Training and Extension,",
    title2: "Don Honorio Ventura State University,  Philippines",
    title3: "",
    image: "/images/board-members/dr-ranie-b-canlas.webp",
  },
  {
    name: "Dr. Marilyn Morales Obod",
    title: "Research Director,",
    title2: "Former Dean of the MAED Program of the Graduate School,",
    title3: "World Citi Colleges, Philippines",
    image: "/images/board-members/dr-marilyn-morales-obod.webp",
  },
  {
    name: "Dr. Aris Ignacio",
    title: "Dean, College of Computing, Engineering and Communication Media,",
    title2: "Southville International School and Colleges, Philippines.",
    title3: "",
    image: "/images/board-members/dr-aris-ignacio.webp",
  },
  {
    name: "Dr. Rosemarie R. Casimiro",
    title: "Dean, College of Public Administration and Disaster Management,",
    title2: "Nueva Ecija University of Science and Technology, Philippines",
    title3: "",
    image: "/images/board-members/dr-rosemarie-r-casimiro.webp",
    back: "top",
  },
  {
    name: "Dr. Nelson B. Guillen Jr., Ph.D., MSM, MDME, CMP, CPM, CDM",
    title: "Assistant Dean for External Affairs and Lasallian Mission Procter and Gamble Philippines Inc., Chair in Marketing Ramon V. del Rosario College of Business, ",
    title2: "De La Salle University, Manila, Philippines.",
    title3: "",
    title4: "",
    image: "/images/board-members/nelson-guillen.jfif",
  },
  {
    name: "Dr. Vilma B. Ramos",
    title: "Program Chair,Graduate School Public Administration, Head,Regional Center for Indigenous Peoples Education,",
    title2: "",
    title3: "Nueva Ecija University of Science and Technology, ",
    title4: "Philippines.",
    image: "/images/board-members/dr-vilma-b-ramos.webp",
  },
  {
    name: "Dr. Algene Malte De Guzman",
    title: "Assistant Professor, Chief of the Center for Instructional Materials Development and Assessment, Polytechnic University of the Philippines,",
    title2: "",
    title3: "Philippines.",
    title4: "",
    image: "/images/board-members/dr-algene-malte-de-guzman.jpg",
  },
  
  {
    name: "Engr. Ludwig O. Federigan, EMDRCM, CBP",
    title:
      "Founder & Chief Strategic Advisor, Young Environmental Forum (Philippines)",
    title2: "Director, Climate Tracker Asia Inc.",
    title3: "",
    image: "/images/board-members/engr-ludwig-o-federigan.webp",
  },
  {
    name: "Mr. Nihar Malali",
    title: "Senior Solutions Architect,",
    title2: "Senior Director National Life Group,",
    title3: "Dallas, Texas, US.",
    image: "/images/board-members/mr-nihar-malali.webp",
  },
  {
    name: "Mr. Sita Rama Praveen Madugula",
    title: "Technology Leader,",
    title2: " Techno Tasks Inc.,",
    title3: "Texas, US.",
    image: "/images/board-members/mr-sita-rama.webp",
  },
  {
    name: "Dr. Maeda L. Kadtong",
    title: "Professor VI,",
    title2: "College of Education, ",
    title3: "Mindanao State University-Maguindanao, Philippines",
    image: "/images/board-members/dr-maeda-l-kadtong.webp",
  },
  {
    name: "Dr. Sheryl May D. Lainez",
    title: "Associate Professor V,",
    title2: "Mindoro State University-Bongabong Campus, Philippines.",
    image: "/images/board-members/dr-sheryl-may-d-lainez.webp",
  },
  {
    name: "Dr. Bernandino P. Malang",
    title: "Associate Professor V,",
    title2: "Bulacan State University, Bustos Campus, Philippines",
    title3: "",
    image: "/images/board-members/dr-bernandino-p-malang.webp",
  },
  {
    name: "Dr. Michael B. Baylon",
    title: "Lecturer,",
    title2: "Mapua University, Philippines",
    title3: "",
    image: "/images/board-members/dr-michael-b-baylon.webp",
  },
  {
    name: "Mr. Cesar D. Almonicar, Jr.",
    title: "Associate Professor I,",
    title2: "Dean, Teacher Education Institute,",
    title3:
      "Dr. Emilio B. Espinosa Sr. Memorial State College of Agriculture and Technology, Philippines.",
    image: "/images/board-members/mr-cesar-d-almonicar-jr.webp",
  },
  {
    name: "Dr. Marlon A. Maglantay",
    title: "Graduate School Professor",
    title2: "Enthusiastic College, Inc. Maguindanao, Philippines",
    image: "/images/board-members/dr-marlon-a-maglantay.webp",
  },
  {
    name: "Mr. Hasmer A. Hamid, RSW, LPT, MPA",
    title: " Project Development Officer (PDO) IV / Team Leader,",
    title2: "Department of Social Welfare and Development Central Office,",
    title3: "Philippines.",
    title4: "",
    image: "/images/board-members/mr-hasmer-a-hamid.webp",
  },
  {
    name: "Dr. Maridel Z.Viernes",
    title: "Faculty,",
    title2:
      "Nueva Ecija University of Science and Technology (NEUST), Sumaca Campus,",
    title3: "Cabanatuan City, Philippines",
    image: "/images/board-members/dr-maridel-z-viernes-image.jpg",
  },
  {
    name: "Dr. Sanjay Nadkarni",
    title:
      "Head of Innovation & Strategy, Arabian Falcon Holding (commercial arm of the Private Office of His Highness Shaikh Omar Bin Zayed Al Nahyan),",
    title2: " UAE",
    image: "/images/board-members/dr-sanjay-nadkarni.webp",
  },
  {
    name: "Dr. Taufiq-Hail Ghilan",
    title: "Assistant Professor,",
    title2: " University of Buraimi,",
    title3: "Al Buraimi, Sultanate of Oman.",
    image: "/images/board-members/dr-taufiq-hail-ghilan.webp",
  },
  {
    name: "Mr. Mardit Nikodemus Nalle",
    title: "Lecturer,",
    title2: "Department of AgriBusiness,",
    title3: "Universitas Timor, Indonesia",
    image: "/images/board-members/mr-mardit-nikodemus-nalle.webp",
  },
  {
    name: "Dr. Mohammed Alias Yusof",
    title: "Professor,",
    title2: "Department of Civil Engineering,",
    title3: "National Defense University of Malaysia,",
    title4: "Malaysia",
    image: "/images/board-members/dr-mohammed-alias-yusof.webp",
  },
  {
    name: "Dr. Deepak L. Waikar",
    title: "Chair, IEEE Education Society Chapter,",
    title2: "Singapore",
    image: "/images/board-members/dr-deepak-l.waikar.webp",
  },
  {
    name: "Dr. Sigamoney Manicka Naicker",
    title: "Visiting Professor, Leeds Trinity University",
    title2: "Adjunct Professor, University of Western Cape",
    title3:
      "Chairperson, Ministerial Committee on Inclusive Education In South Africa.",
    image: "/images/board-members/dr-sigamoney-manicka-naicker.webp",
  },
  {
    name: "Dr. SANTHOSH U.N",
    title: "Research Associate (Agronomy), Organic Farming Research Center,",
    title2: "KSNUAHS, Shivamogga,",
    title3: "India.",
    image: "/images/board-members/dr-santhosh-u-n.webp",
  },
  {
    name: "Dr. Diwakar Ramanuj Tripathi",
    title: "Head PGTD of Computer Science,",
    title2: "S.S. Maniar College of Computer and Management, Nagpur, India.",
    image: "/images/board-members/dr-diwakar-ramanuj-tripathi.webp",
  },
  {
    name: "Dr. Yogesh K Jain",
    title: "Professor & Researcher - Finance & Accounts",
    title2: "Dr. D. Y. Patil Vidyapeeth, Centre for Online Learning,",
    title3: "Pune, India",
    image: "/images/board-members/dr.yogesh-k-jain.webp",
  },
  {
    name: "Dr. Vijayalakshmi Chintamaneni",
    title: "Associate Professor,",
    title2: "Department of ECE,",
    title3: "Vignan Institute of Technology and Science,",
    title4: "Hyderabad, Telangana, India.",
    image: "/images/board-members/dr-vijayalakshmi-chintamaneni.webp",
  },
  
];

export default advisoryBoardMembers;
